local_backend: true

backend:
  name: github
  repo: bugracdnc/neslihanogretmenim
  branch: master
  base_url: https://neslihanogretmenim-auth.bugracaliskandinc.workers.dev/
  auth_endpoint: /auth

media_folder: "public/uploads"
public_folder: "/neslihanogretmenim/uploads"

collections:
  - name: "etkinlikler"
    label: "Etkinlikler"
    folder: "src/content/etkinlikler"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      
      - { label: "Kısa Açıklama", name: "description", widget: "text" }

      - { 
          label: "Kategori/Etiket", 
          name: "tags", 
          widget: "select", 
          multiple: true, # Birden fazla kategori seçimine izin verir
          options: [
            "1. Sınıf", 
            "2. Sınıf", 
            "3. Sınıf", 
            "4. Sınıf", 
            "Belirli Günler ve Haftalar", 
            "Görsel Sanatlar",
            "Matematik",
            "Türkçe",
            "Okuma Yazma",
            "Sınıf İçi Oyunlar"
          ]
        }
      # Görsel (Thumbnail) için özel yapılandırma
      - { 
          label: "Kapak Görseli", 
          name: "thumbnail", 
          widget: "file", 
          required: false,
          media_folder: "/public/images/publish/thumbnails", # Baştaki / işareti hayati önem taşır!
          public_folder: "/images/publish/thumbnails"
        }
        
      - { 
          label: "İlişikli Dosya", 
          name: "file", 
          widget: "file", 
          required: false,
          media_folder: "/public/images/publish/files", # Baştaki / işareti hayati önem taşır!
          public_folder: "/images/publish/files"
        }

      - { label: "İçerik", name: "body", widget: "markdown", required:false }
