local_backend: true

backend:
  name: github
  repo: bugracdnc/neslihanogretmenim
  branch: master
  base_url: https://neslihanogretmenim-auth.bugracaliskandinc.workers.dev/
  auth_endpoint: /auth

media_folder: "public/uploads"
public_folder: "/neslihanogretmenim/uploads"

collections:
  - name: "etkinlikler"
    label: "Etkinlikler"
    folder: "src/content/etkinlikler" # This is where the CMS will save the markdown files
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - {
          label: "Açıklama",
          name: "description",
          widget: "text",
          hint: "Kartların üzerinde görünecek kısa açıklama.",
        }
      - {
          label: "Kategoriler",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "1. Sınıf",
              "2. Sınıf",
              "3. Sınıf",
              "4. Sınıf",
              "Belirli Günler",
              "Matematik",
              "Türkçe",
              "Oyun",
              "Görsel Sanatlar",
            ],
        }
      - {
          label: "Kapak Görseli",
          name: "thumbnail",
          widget: "image",
          required: false,
          hint: "Opsiyonel: Varsa etkinliğin resmi.",
        }
      - {
          label: "İndirilecek Dosya",
          name: "file",
          widget: "file",
          required: false,
          hint: "PDF, ZIP, DOCX vb.",
        }
      - {
          label: "Detaylı İçerik",
          name: "body",
          widget: "markdown",
          required: false,
          hint: "Eğer ileride kendi sayfasında uzun uzun yazmak istersen diye.",
        }
